name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run tests
      run: |
        pytest tests/
    
    - name: Train model
      run: |
        python src/train.py
    
    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model.joblib

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Download model artifact
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
          
    - name: Configure Docker to use GCR
      run: |
        gcloud auth configure-docker gcr.io

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/YOUR_PROJECT_ID/my-app:latest .

    - name: Push Docker Image to GCR
      run: |
          docker push gcr.io/YOUR_PROJECT_ID/my-app:latest
      
   # - name: Build and push
   #   uses: docker/build-push-action@v2
   #   with:
    #    context: .
     #   push: true
      #  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ml-project:latest

  deploy:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy application (simulation)
      run: |
        echo "Deploying application to production..."
        # Here you would typically have steps to deploy to your cloud platform
        # For example: AWS ECS, Google Cloud Run, or Kubernetes
